import { LinkedinProfile } from '../profile.entity';

export class ProfileMapper {
  static toResponse(profile: LinkedinProfile) {
    return {
      id: profile.id,
      full_name: profile.full_name,
      first_name: profile.first_name,
      last_name: profile.last_name,
      middle_name: profile.middle_name,
      middle_initial: profile.middle_initial,
      gender: profile.gender,
      linkedin_url: profile.linkedin_url,
      linkedin_username: profile.linkedin_username,
      linkedin_id: profile.linkedin_id,
      industry: profile.industry,
      job_title: profile.job_title,
      job_title_role: profile.job_title_role,
      job_title_levels: profile.job_title_levels,
      job_company_name: profile.job_company_name,
      job_company_website: profile.job_company_website,
      job_company_size: profile.job_company_size,
      job_company_founded: profile.job_company_founded,
      job_company_industry: profile.job_company_industry,
      job_company_linkedin_url: profile.job_company_linkedin_url,
      job_company_location_name: profile.job_company_location_name,
      job_company_location_locality: profile.job_company_location_locality,
      job_company_location_country: profile.job_company_location_country,
      job_company_location_geo: profile.job_company_location_geo,
      location_name: profile.location_name,
      location_locality: profile.location_locality,
      location_region: profile.location_region,
      location_country: profile.location_country,
      location_continent: profile.location_continent,
      location_geo: profile.location_geo,
      linkedin_connections: profile.linkedin_connections,
      inferred_salary: profile.inferred_salary,
      inferred_years_experience: profile.inferred_years_experience,
      summary: profile.summary,
      phone_numbers: profile.phone_numbers,
      emails: profile.emails,
      interests: profile.interests,
      skills: profile.skills,
      experience: profile.experience,
      education: profile.education,
      profiles: profile.profiles,
      certifications: profile.certifications,
      languages: profile.languages,
      work_email: profile.work_email,
      job_summary: profile.job_summary,
      job_last_updated: profile.job_last_updated,
      job_start_date: profile.job_start_date,
      location_last_updated: profile.location_last_updated,
      twitter_url: profile.twitter_url,
      twitter_username: profile.twitter_username,
      github_url: profile.github_url,
      github_username: profile.github_username,
      mobile_phone: profile.mobile_phone,
      birth_year: profile.birth_year,
      birth_date: profile.birth_date,
      createdAt: profile.createdAt,
      updatedAt: profile.updatedAt,
    };
  }

  static toSearchResponse(profile: LinkedinProfile) {
    return {
      id: profile.id,
      full_name: profile.full_name,
      first_name: profile.first_name,
      last_name: profile.last_name,
      job_title: profile.job_title,
      job_company_name: profile.job_company_name,
      industry: profile.industry,
      location_name: profile.location_name,
      location_country: profile.location_country,
      skills: profile.skills,
      linkedin_url: profile.linkedin_url,
      linkedin_username: profile.linkedin_username,
      inferred_years_experience: profile.inferred_years_experience,
      emails: profile.emails,
    };
  }

  static toListResponse(profile: LinkedinProfile) {
    return {
      id: profile.id,
      full_name: profile.full_name,
      first_name: profile.first_name,
      last_name: profile.last_name,
      job_title: profile.job_title,
      job_company_name: profile.job_company_name,
      industry: profile.industry,
      location_name: profile.location_name,
      location_country: profile.location_country,
      skills: profile.skills,
      linkedin_url: profile.linkedin_url,
      inferred_years_experience: profile.inferred_years_experience,
      createdAt: profile.createdAt,
    };
  }
}
